//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement2.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssetLocationEntities : DbContext
    {
        public AssetLocationEntities()
            : base("name=AssetLocationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetLocation> AssetLocations { get; set; }
        public virtual DbSet<Assetlocation1> Assetlocations1 { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
    }
}
